version: '2'
services:
    tablereservation-app:
        image: tablereservation
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tablereservation-postgresql:5432/TableReservation
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tablereservation-postgresql:
        extends:
            file: postgresql.yml
            service: tablereservation-postgresql
