version: '2'
services:
    tablereservation-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/TableReservation/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=TableReservation
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
